// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXhCq24m5HrMXrVlfh2DZ0k3r07WYEu8M',
    appId: '1:974568859270:web:fa430ac0a0353c8b5a5307',
    messagingSenderId: '974568859270',
    projectId: 'rocket-x-b714f',
    authDomain: 'rocket-x-b714f.firebaseapp.com',
    storageBucket: 'rocket-x-b714f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsx37MngWwRDjOaL6mwri7QgVlkWYKpZU',
    appId: '1:974568859270:android:9e9438516a5df8bb5a5307',
    messagingSenderId: '974568859270',
    projectId: 'rocket-x-b714f',
    storageBucket: 'rocket-x-b714f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCIwtkg0BiQFD7cizUOqdBibQHxo-KND8',
    appId: '1:974568859270:ios:e15cf2f32d90df875a5307',
    messagingSenderId: '974568859270',
    projectId: 'rocket-x-b714f',
    storageBucket: 'rocket-x-b714f.firebasestorage.app',
    iosBundleId: 'com.example.xclone',
  );
}
